### PROGRAM - 7 : Grey Wolf Optimization

In [1]:
import numpy as np

def objective_function(x):
    return np.sum(x**2)

def grey_wolf_optimization(obj_func, dim, n_wolves, max_iter, bounds):
    wolves = np.random.uniform(bounds[0], bounds[1], (n_wolves, dim))
    alpha, beta, delta = np.zeros(dim), np.zeros(dim), np.zeros(dim)
    alpha_score, beta_score, delta_score = float('inf'), float('inf'), float('inf')
    print("Initial Wolves' Positions:")
    print(wolves)

    for t in range(max_iter):
        for i in range(n_wolves):
            fitness = obj_func(wolves[i])
            if fitness < alpha_score:
                delta_score, delta = beta_score, beta.copy()
                beta_score, beta = alpha_score, alpha.copy()
                alpha_score, alpha = fitness, wolves[i].copy()
            elif fitness < beta_score:
                delta_score, delta = beta_score, beta.copy()
                beta_score, beta = fitness, wolves[i].copy()
            elif fitness < delta_score:
                delta_score, delta = fitness, wolves[i].copy()

        a = 2 - t * (2 / max_iter)

        for i in range(n_wolves):
            for j in range(dim):
                r1, r2 = np.random.rand(), np.random.rand()
                A1, C1 = 2*a*r1 - a, 2*r2
                D_alpha = abs(C1*alpha[j] - wolves[i][j])
                X1 = alpha[j] - A1*D_alpha

                r1, r2 = np.random.rand(), np.random.rand()
                A2, C2 = 2*a*r1 - a, 2*r2
                D_beta = abs(C2*beta[j] - wolves[i][j])
                X2 = beta[j] - A2*D_beta

                r1, r2 = np.random.rand(), np.random.rand()
                A3, C3 = 2*a*r1 - a, 2*r2
                D_delta = abs(C3*delta[j] - wolves[i][j])
                X3 = delta[j] - A3*D_alpha

                wolves[i][j] = (X1 + X2 + X3) / 3

        print(f"\nIteration {t + 1}/{max_iter}: Best Fitness = {alpha_score:.5f}")

    print("\nOptimization Complete!")
    print("Best Position Found (Alpha Wolf): ", alpha)
    print("Best Fitness Found: ", alpha_score)

dim = 5
n_wolves = 10
max_iter = 20
bounds = (-10, 10)

grey_wolf_optimization(objective_function, dim, n_wolves, max_iter, bounds)

Initial Wolves' Positions:
[[ 8.34717937 -9.282919   -6.09219033  6.56713407 -5.24577887]
 [-9.86273405  7.26448098  9.47272289 -0.8332156   0.10263821]
 [ 1.72236518  7.5069034   1.6765496  -3.15079844  4.14742121]
 [ 3.37549051  7.212396   -1.78558581 -9.12922101 -6.0408405 ]
 [-3.57588277  9.34767273  9.89161212  3.8043905  -5.52416814]
 [ 7.39514366 -5.63752698 -2.74083857 -8.86296845 -3.4220175 ]
 [ 2.72673569  7.41361859 -4.36807709  1.82676115  9.96996401]
 [-0.86308859  8.5937848  -9.74686043 -0.03949087  7.53724758]
 [ 5.5906346   0.99830152  0.98877186 -1.51326974 -9.02042814]
 [ 9.15700944 -5.52259203 -5.72090827 -0.83861799  3.89279594]]

Iteration 1/20: Best Fitness = 89.25959

Iteration 2/20: Best Fitness = 59.20983

Iteration 3/20: Best Fitness = 35.77969

Iteration 4/20: Best Fitness = 18.60832

Iteration 5/20: Best Fitness = 2.95994

Iteration 6/20: Best Fitness = 0.67326

Iteration 7/20: Best Fitness = 0.67326

Iteration 8/20: Best Fitness = 0.49986

Iteration 9/20: B